version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker build
          no_output_timeout: 60m
          command: |
            for i in {1..5}; do
              docker build -t miykael/nipype_tutorial:$CIRCLE_BRANCH . && break || sleep 15
            done

  notebooks_basic:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: run basic notebooks
          no_output_timeout: 90m
          command: |
            docker run -it --rm miykael/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s /home/neuro/nipype_tutorial/tests/test_notebooks_basic.py

  notebooks_introduction:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: run basic notebooks
          no_output_timeout: 90m
          command: |
            docker run -it --rm miykael/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s /home/neuro/nipype_tutorial/tests/test_notebooks_introduction.py

  notebooks_example:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: run example notebooks
          no_output_timeout: 120m
          command: |
            docker run -it --rm miykael/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s /home/neuro/nipype_tutorial/tests/test_notebooks_example.py

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - notebooks_basic:
          requires:
            - build
      - notebooks_introduction:
          requires:
            - build
      - notebooks_example:
          requires:
            - build
